language: node_js
node_js:
- '8'
- '9'
- '10'
cache:
  directories:
  - node_modules
before_script:
- npm run build
- npm run build.browser
script:
- npm run test
- npx embedme README.md

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
